version: '3'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27027'
    volumes:
      - 'mongo:/data/db'
    networks:
      - backend
  api:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongo/table-db
      - JWT_SECRET=jwtsecret
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongo: